### ISSUE TITLE
Unsupported compression tool | zstd

### ISSUE THREAD

**Issue by jsacerot** [grimbough/Rarr#8]
I'm trying to read data from [https://noaa-nws-aorc-v1-1-1km.s3.amazonaws.com/2019.zarr/TMP_2maboveground](https://noaa-nws-aorc-v1-1-1km.s3.amazonaws.com/2019.zarr/TMP_2maboveground), which is ```zstd``` compressed. I get the ```Unsupported compression tool``` warning message. 

I notice some support has been included in the code for ```zstd```. Would it be fully supported soon?

Thanks!

**Comment by grimbough** [comment]
You haven't included the output of `sessionInfo()`, so I'm not sure exactly which version of Rarr you're using, but this should already be available in the devel version at Bioconductor, and also the devel branch here.

You can install that with: `BiocManager::install('grimbough/Rarr')`

**Comment by jsacerot** [comment]
@grimbough Thank you for getting back to me so quickly. I installed the dev version from  ```grimbough/Rarr```, and it did the trick.
